generator/urls.py
from django.conf.urls import url

from . import views

app_name = 'generator'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),

    url(r'^api/game/(?P<game_id>[0-9]+)/$', views.game_load, name='game'),
    url(r'^api/game/create/$', views.game_create, name="game_create"),
    url(r'^api/game/update/$', views.game_update, name="game_update"),
    url(r'^api/components/create/$', views.components_create, name='components_create'),
    url(r'^api/components/update/$', views.components_update, name='components_update'),
    url(r'^api/components/delete/$', views.components_delete, name='components_delete'),
    url(r'^api/details/create/$', views.details_create, name='details_create'),
    url(r'^api/details/update/$', views.details_update, name='details_update'),
    url(r'^api/details/delete/$', views.details_delete, name='details_delete'),

    url(r'^api/generate/$', views.generate, name='generate'),
    url(r'^api/sync/$', views.sync_sheet, name='syncsheet'),
    url(r'^oauth2callback/$', views.oauth2_callback, name='oauth2callback'),
    url(r'^deletecreds/$', views.delete_creds, name='deletecreds'),#for debugging (TODO: remove in prod)
]

infinitelabyrinth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
		url(r'', include('generator.urls')),
    url(r'^admin/', admin.site.urls),
]

generator/models.py
import json

from django.db import models
from django.contrib.auth.models import User
from django.contrib.postgres.fields import JSONField

from oauth2client.contrib.django_util.models import CredentialsField

from core.helpers import parse_sheet_url

class CredentialsModel(models.Model):
  id = models.OneToOneField(User, primary_key=True)
  credential = CredentialsField()

class Game(models.Model):
  name = models.CharField(max_length=50, default='New Campaign', blank=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  scrambler_data = JSONField(blank=True, default=json.dumps(dict()))
  scrambler_endpoints = JSONField(blank=True, default=json.dumps(dict()))
  sheet_url = models.URLField(null=True)
  map_transforms = JSONField(blank=True, default=json.dumps(dict()))
  map_names_toggle = models.BooleanField(default=False)

  def __str__(self):
    if len(self.name) > 0:
      return '%s' % (self.name)
    else:
      return 'Game ID %s' % (self.pk)

  def sheet_id(self):
    if self.sheet_url:
      return parse_sheet_url(self.sheet_url)
    else:
      return None

class Component(models.Model):
  name = models.CharField(max_length=50, default='', blank=True)
  game = models.ForeignKey(Game, on_delete=models.CASCADE)
  x = models.DecimalField(max_digits=19, decimal_places=15)
  y = models.DecimalField(max_digits=19, decimal_places=15)
  width = models.PositiveSmallIntegerField(default=1, blank=True)
  height = models.PositiveSmallIntegerField(default=1, blank=True)
  isActive = models.BooleanField(default=False)
  LOCATION = 'L'
  PARTY = 'P'
  CREATURE = 'C'
  TRANSPORT = 'T'
  OTHER = 'O'
  CATEGORY_CHOICES = (
    (LOCATION, 'Location'),
    (PARTY, 'Party'),
    (CREATURE, 'Creature'),
    (TRANSPORT, 'Transport'),
    (OTHER, 'Other'),
  )
  category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default=OTHER, blank=True)

  def __str__(self):
    if len(self.name) > 0:
      return '%s (%s)' % (self.name, self.get_category_display())
    else:
      return 'ID# %s (%s)' % (self.pk, self.get_category_display())

class Detail(models.Model):
  component = models.ForeignKey(Component, on_delete=models.CASCADE)
  content = models.TextField(blank=True)

  def __str__(self):
    if len(self.content) > 50:
      return '%s' % (self.content[:50] + "...")
    else:
      return '%s' % (self.content)
  

generator/forms.py
from django.forms import ModelForm
from .models import Game, Component, Detail

class GameForm(ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'scrambler_data', 'scrambler_endpoints', 'map_transforms', 'map_names_toggle']

class ComponentForm(ModelForm):
    class Meta:
        model = Component
        fields = ['name', 'game', 'x', 'y', 'isActive', 'category']

class DetailForm(ModelForm):
    class Meta:
        model = Detail
        fields = ['content', 'component']

generator/views.py
#TODO: 'require authenticated user' decorators

import json

from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

from infinitelabyrinth import settings

from .models import Game, Component, Detail, CredentialsModel
from .forms import GameForm, ComponentForm, DetailForm

from core.namer import Namer
from core.scrambler import Scrambler
from core.helpers import process_sheet_data, parse_sheet_url

#Google OAuth2
from oauth2client.client import OAuth2WebServerFlow
from oauth2client.contrib.django_util.storage import DjangoORMStorage
from oauth2client.contrib import xsrfutil
import httplib2
from googleapiclient import discovery

flow = OAuth2WebServerFlow(client_id=settings.GOOGLE_OAUTH2_CLIENT_ID,
                           client_secret=settings.GOOGLE_OAUTH2_CLIENT_SECRET,
                           scope='https://www.googleapis.com/auth/spreadsheets.readonly')
default_game_id = 3

def index(request):
    if request.user.is_authenticated:
        print("user %s is authenticated" % (request.user.username))
        return user_page(request)
    else:
        print("user is not authenticated")
        return welcome(request)

def user_page(request):
    #TODO: should return last edited game
    game = Game.objects.filter(user_id=request.user.id).first()
    if not game:
        game = Game.objects.create(user_id=request.user.id, scrambler_endpoints="{}", scrambler_data="{}")
    context = {
        'game_id': game.id,
        'categories':Component.CATEGORY_CHOICES,
    }
    return render(request, 'generator/index.html', context)

def welcome(request):
    # game = Game.objects.get(id=default_game_id)
    game = Game.objects.all().first()
    context = {
        'endpoints': json.loads(game.scrambler_endpoints),
        'game_id': game.id,
        'categories':Component.CATEGORY_CHOICES,
    }
    return render(request, 'generator/welcome.html', context)

def signup_view(request):
    #TODO: validate password, username length
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = User.objects.create_user(username, password=password)
        user.save()
        print('Successfully created user %s' % user.username)
        login(request, user)
        return HttpResponseRedirect("/")
    else:
        return HttpResponseBadRequest()

def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect("/")
        else:
            # TODO: Return an 'invalid login' error message.
            return HttpResponseBadRequest()
    else:
        return HttpResponseBadRequest()

def logout_view(request):
    logout(request)
    return HttpResponseRedirect("/")

def game_load(request, game_id):
    game = Game.objects.filter(id=game_id).values()[0]
    game.pop("scrambler_data")
    endpoints = dict(json.loads(game.pop("scrambler_endpoints")))
    game["endpoints"] = endpoints
    components = list(Component.objects.filter(game=game["id"]).values())
    game["components"] = components
    for component in game["components"]:
        details = list(Detail.objects.filter(component=component["id"]).values())
        component["details"] = details
    response = dict(game=game)
    return JsonResponse(response)

def game_create(request):
    #TODO: does this need to be more flexible? (ex. creating game with name, scrambler data)
    #TODO: load newly created game on the frontend
    response = dict()
    if request.method == 'POST':
        game = Game.objects.create(user_id=request.user.id)
        game.save()
        response['game'] = dict(Game.objects.filter(id=game.id).values()[0])
        return JsonResponse(response)
    else:
        #TODO
        return JsonResponse(response)

def game_update(request):
    response = dict()
    if request.method == 'POST':
        game_data = json.loads(request.body.decode('utf-8'))
        game = get_object_or_404(Game, id=int(game_data['id']))
        form = GameForm(game_data, instance=game)
        if form.is_valid():
            form.save()
            response['game'] = dict(Game.objects.filter(id=game.id).values()[0])
            return JsonResponse(response)
        else:
            #TODO
            print(form.errors)
            print('invalid form')
    return JsonResponse(response)

def components_create(request):
    response = dict()
    if request.method == 'POST':
        component_data = json.loads(request.body.decode('utf-8'))
        form = ComponentForm(component_data)
        if form.is_valid():
            component = form.save()
            response['component'] = dict(Component.objects.filter(id=component.id).values()[0])
            return JsonResponse(response)
        else:
            # TODO
            print("suk it")
    return JsonResponse(response)

def components_update(request):
    response = dict()
    if request.method == 'POST':
        component_data = json.loads(request.body.decode('utf-8'))
        component = get_object_or_404(Component, id=int(component_data['id']))
        form = ComponentForm(component_data, instance=component)
        if form.is_valid():
            form.save()
            response['component'] = dict(Component.objects.filter(id=component.id).values()[0])
            return JsonResponse(response)
    return JsonResponse(response)

def components_delete(request):
    #TODO: return some responseS
    response = dict()
    if request.method == 'POST':
        component_data = json.loads(request.body.decode('utf-8'))
        component = get_object_or_404(Component, id=int(component_data['id']))
        component.delete()
        return JsonResponse(response)
    return JsonResponse(response)

def details_create(request):
    response = dict()
    if request.method == 'POST':
        detail_data = json.loads(request.body.decode('utf-8'))
        form = DetailForm(detail_data)
        if form.is_valid():
            detail = form.save()
            response['detail'] = dict(Detail.objects.filter(id=detail.id).values()[0])
            return JsonResponse(response)
        else:
            # TODO
            print(form.errors)
            print("suk it")
    return JsonResponse(response)

def details_update(request):
    response = dict()
    if request.method == 'POST':
        detail_data = json.loads(request.body.decode('utf-8'))
        detail = get_object_or_404(Detail, id=int(detail_data['id']))
        form = DetailForm(detail_data, instance=detail)
        if form.is_valid():
            form.save()
            response['detail'] = dict(Detail.objects.filter(id=detail.id).values()[0])
            return JsonResponse(response)
    return JsonResponse(response)

def details_delete(request):
    response = dict()
    if request.method == 'POST':
        detail_data = json.loads(request.body.decode('utf-8'))
        detail = get_object_or_404(Detail, id=int(detail_data['id']))
        detail.delete()
        return JsonResponse(response)
    return JsonResponse(response)

def generate(request):
    # TODO: cleanup
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        format_text = data.get('text', '')
        game_id = data.get('game_id')
        text = None
        game = Game.objects.get(id=game_id)
        if game:
            data = json.loads(game.scrambler_data)
            text = Scrambler(data['tables']).scramble(format_text)
            text = Namer(data['corpora']).generate(text)
        else:
            game = Game.objects.filter(id=1).first()
            data = json.loads(game.scrambler_data)
            text = Scrambler(data['tables']).scramble(format_text)
            text = Namer(data['corpora']).generate(text)
        data = {
            'detail':text
        }
        return JsonResponse(data)
    else:
        message = "Something went wrong"
        return JsonResponse({'status':'false','message':message}, status=500)

def sync_sheet(request):
    # possible error: oauth credentials can expire (?) but this will still try to use the old creds
    # TODO: loading spinner on the frontend while processing
    # TODO: ensure game id is provided; if no URL provided, fall back to last URL used
    if request.user.is_authenticated and request.method == 'POST':
        game_id = request.POST.get("game-id")
        game = get_object_or_404(Game, id=game_id)
        sheet_url = request.POST.get("sheet-url") or game.sheet_url
        result = None
        storage = DjangoORMStorage(CredentialsModel, 'id', request.user, 'credential')
        credentials = storage.get()
        if credentials is None or credentials.invalid == True:
            flow.params['state'] = xsrfutil.generate_token(settings.SECRET_KEY, request.user)
            flow.redirect_uri = '%s%s' % (request.META['HTTP_REFERER'],'oauth2callback')
            auth_uri = flow.step1_get_authorize_url()
            return HttpResponseRedirect(auth_uri)
        else:
            # google sheets API
            http = httplib2.Http()
            http = credentials.authorize(http)
            discoveryUrl = ('https://sheets.googleapis.com/$discovery/rest?'
                            'version=v4')
            service = discovery.build('sheets', 'v4', http=http,
                                      discoveryServiceUrl=discoveryUrl)
            spreadsheetId = None
            #TODO: cleaner error handling/fallback
            if sheet_url:
                spreadsheetId = parse_sheet_url(sheet_url)
            else:
                return HttpResponseBadRequest()

generator/templates/generator/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
<title>Infinite Labyrinth</title>
  <link rel="stylesheet" type="text/css" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
  <link rel="stylesheet" type="text/css" href="{% static "generator/css/generator.css" %}">
  <link rel="stylesheet" type="text/css" href="{% static "generator/css/mapper.css" %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">

    <ul class="nav navbar-nav">
      <li>
        <a href="/">Guide</a>
      </li>
      {% if user.is_authenticated %}
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Games <span class="caret"></span>
        </a>
        <ul id="games-dropdown" class="dropdown-menu">
          {% for game in user.game_set.all reversed %}
          <li><a data-id="{{ game.id }}" href="#">{{ game.name }}</a></li>
          {% endfor %}
          <li class="divider"></li>
          <li><a id="newGame" href="#">Start New Game</a></li>
        </ul>
      </li>
      {% endif %}
    </ul>

    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <span class="glyphicon glyphicon-user"></span> Welcome, {{ user.username }}
        </a>
        <ul class="dropdown-menu">
          <li><a href="/logout">Logout</a></li>
        </ul>
      </li>
      {% else %}
      <li><p class="navbar-text">Already have an account?</p></li>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Log in</b></a>
          <ul id="login-dp" class="dropdown-menu">
            <li>
              <div class="row">
                <div class="col-md-12">
                  <form class="form" role="form" method="post" action="login/" accept-charset="UTF-8" id="login-nav">
                    {% csrf_token %}
                    <div class="form-group">
                      <label class="sr-only" for="inputUsername">Username</label>
                      <input type="text" class="form-control" id="inputUsername" placeholder="Username" required name="username">
                    </div>
                    <div class="form-group">
                      <label class="sr-only" for="inputPassword">Password</label>
                      <input type="password" class="form-control" id="inputPassword" placeholder="Password" required name="password">
                    </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </div>
                  </form>
                </div>
              </div>
            </li>
          </ul>
        </li>
      {% endif %}
    </ul>

  </div>
</nav>

{% block content %}{% endblock %}

{% block javascript %}{% endblock %}

</body>
</html>

generator/templates/generator/canvastest.html
{% extends "generator/base.html" %}
{% load staticfiles %}

{% block javascript %}
  <script>
    var SCALE = 5;
    var LINEWIDTH = SCALE*0.05;
    var ACTIVECOLOR = 'white';
    var HOVERCOLOR= '#aaaaaa';
    var INACTIVECOLOR = '#555555';

    function Room (x, y, width, height, isActive, id) {
      this.id = id;
      this.isActive = isActive;
      this.hover = false;
      this.colors = {
        active: ACTIVECOLOR,
        hover: HOVERCOLOR,
        inactive: INACTIVECOLOR
      };
      this.x = x*SCALE;
      this.y = y*SCALE;
      this.width = width*SCALE;
      this.height = height*SCALE;
      this.contains = function (x, y) {
        return this.x <= x && x <= this.x + this.width &&
               this.y <= y && y <= this.y + this.height;
      };
      this.draw = function (ctx) {
        if (this.isActive) {
          ctx.fillStyle = this.colors.active;
        } else if (this.hover) {
          ctx.fillStyle = this.colors.hover;
        } else {
          ctx.fillStyle = this.colors.inactive
        }
        ctx.fillRect(this.x, this.y, this.width, this.height);
      };
    };

    function Corridor (path, isActive, id) {
      this.id = id;
      this.isActive = isActive;
      this.hover = false;
      this.colors = {
        active: ACTIVECOLOR,
        hover: HOVERCOLOR,
        inactive: INACTIVECOLOR
      };
      this.rects = [];
      for (var i = 0; i < path.length-1; i++){
        var x = path[i].x*SCALE;
        var y = path[i].y*SCALE;
        var nextX = path[i+1].x*SCALE;
        var nextY = path[i+1].y*SCALE;
        var width = Math.abs(nextX-x) || SCALE;
        var height = Math.abs(nextY-y) || SCALE;
        var rect = {
          x: x,
          y: y,
          width: width,
          height: height
        };
        this.rects.push(rect);
      }
      this.contains = function (x, y) {
        for (var i = 0; i < this.rects.length; i++) {
          var rect = this.rects[i];
          if (rect.x <= x && x <= rect.x + rect.width &&
              rect.y <= y && y <= rect.y + rect.height) {
            return true;
          }
        }
        return false;
      };
      this.draw = function (ctx) {
        if (this.isActive) {
          ctx.fillStyle = this.colors.active;
        } else if (this.hover) {
          ctx.fillStyle = this.colors.hover;
        } else {
          ctx.fillStyle = this.colors.inactive;
        }
        for (var i = 0; i < this.rects.length; i++) {
          var rect = this.rects[i];
          ctx.fillRect(rect.x, rect.y, rect.width, rect.height);
        }
      };
    };

    function Door (x, y, direction, isOpen, id) {
      this.id = id;
      this.isOpen = isOpen;
      this.colors = {
        openFill: INACTIVECOLOR,
        openOutline: 'black',
        closedFill: 'black',
        closedOutline: INACTIVECOLOR
      };
      this.width = SCALE/2;
      this.height = this.width;
      var offset = SCALE/4;
      x = x*SCALE;
      y = y*SCALE;
      switch (direction) {
        case 'north':
          this.x = x+offset;
          this.y = y-offset;
          break;
        case 'south':
          this.x = x+offset;
          this.y = y-offset+SCALE;
          break;
        case 'east' :
          this.x = x-offset+SCALE;
          this.y = y+offset;
          break;
        case 'west' :
          this.x = x-offset;
          this.y = y+offset;
      }
      this.contains = function (x, y) {
        return this.x <= x && x <= this.x + this.width &&
               this.y <= y && y <= this.y + this.height;
      };
      this.draw = function(ctx) {
        if (this.isOpen) {
          ctx.fillStyle = this.colors.openFill;
          ctx.strokeStyle = this.colors.openOutline;
        } else {
          ctx.fillStyle = this.colors.closedFill;
          ctx.strokeStyle = this.colors.closedOutline;
        }
        ctx.lineWidth=LINEWIDTH;
        ctx.fillRect(this.x, this.y, this.width, this.height);
        ctx.strokeRect(this.x, this.y, this.width, this.height);
      };
    };

    // var rooms = [
    //   new Room(1, 1, 5, 5, false, 1),
    //   new Room(7, 8, 3, 3, false, 2)
    // ];
    // var corridors = [
    //   new Corridor([
    //     { x : 6, y : 1 },
    //     { x : 8, y : 1 },
    //     { x : 8, y : 8 }
    //   ], false, 1)
    // ];
    // var doors = [
    //   new Door(5, 1, 'east', true, 1),
    //   new Door(1, 1, 'west', false, 2),
    //   new Door(8, 8, 'north', true, 3),
    //   new Door(9, 10, 'east', false, 4)
    // ];
    
    var dungeonMapper = {
      canvas : document.getElementById("canvas"),
      transforms : {
        scaleFactor : 5.00,
        panX : 0,
        panY : 0,
        prevPanX : 0,
        prevPanY : 0
      },
      start: function () {
        this.context = this.canvas.getContext("2d");
        this.canvas.addEventListener('click', this.handleClick.bind(this), false);
        this.canvas.addEventListener('mousedown', this.handleMouseDown.bind(this), false);
        this.canvas.addEventListener('mouseup', this.handleMouseUp.bind(this), false);
        this.canvas.addEventListener('mousemove', this.handleMouseMove.bind(this), false);
        this.canvas.addEventListener('DOMMouseScroll', this.handleScroll.bind(this), false);
        this.canvas.addEventListener('mousewheel', this.handleScroll.bind(this), false);
        this.draw();
      },
      getMousePos: function (e, canvas) {
        var rect = canvas.getBoundingClientRect();
        var rawX = e.clientX - rect.left;
        var rawY = e.clientY - rect.top
        var transformedX = rawX/this.transforms.scaleFactor-this.transforms.prevPanX;
        var transformedY = rawY/this.transforms.scaleFactor-this.transforms.prevPanY;
        return {
          x: transformedX,
          y: transformedY
        };
      },
      checkCollisions: function (components, mousePos, callback) {
        //TODO: it is currently possible to hover/click on two neighboring components at once
        for (var i = 0; i < components.length; i++){
          var isColliding = components[i].contains(mousePos.x, mousePos.y) ? true : false;
          callback(components[i], isColliding);
        }
      },
      handleClick: function (e) {
        //TODO: don't set components to active if the user was dragging to pan the view
        //TODO: clicking a door shouldn't affect the components beneath it
        e.preventDefault();
        var mousePos = this.getMousePos(e, this.canvas);
        this.checkCollisions(this.doors, mousePos, function(door, isColliding) {
          if (isColliding) {
            door.isOpen = !door.isOpen;
            console.log("door #: " + door.id);
          }
        });
        this.checkCollisions(this.rooms, mousePos, function(room, isColliding) {
          if (isColliding) {
            room.isActive = true;
            console.log(room.id);
          } else {
            room.isActive = false;
          }
        });
        this.checkCollisions(this.corridors, mousePos, function(corridor, isColliding) {
          if (isColliding) {
            corridor.isActive = true;
            console.log(corridor.id);
          } else {
            corridor.isActive = false;
          }
        });
        this.draw();
      },
      handleMouseDown: function (e) {
        e.preventDefault();
        this.mouseIsDown = true;
        this.prevMouseDownPos = this.getMousePos(e, this.canvas);
      },
      handleMouseUp: function (e) {
        e.preventDefault();
        this.mouseIsDown = false;
        var mousePos = this.getMousePos(e, this.canvas);
        this.transforms.prevPanX += mousePos.x - this.prevMouseDownPos.x;
        this.transforms.prevPanY += mousePos.y - this.prevMouseDownPos.y;
      },
      handleMouseMove: function (e) {
        e.preventDefault();
        var mousePos = this.getMousePos(e, this.canvas);
        if (this.mouseIsDown) {
          this.handleDrag(mousePos);
        } else {
          this.handleHover(mousePos);
        }
        this.draw(); //TODO: use animationFrame instead of manually calling draw()
      },
      handleDrag: function (mousePos) {
        this.transforms.panX = this.transforms.prevPanX + mousePos.x - this.prevMouseDownPos.x;
        this.transforms.panY = this.transforms.prevPanY + mousePos.y - this.prevMouseDownPos.y;
      },
      handleHover: function (mousePos) {
        this.checkCollisions(this.rooms, mousePos, function(room, isColliding){
          if (isColliding) {
            room.hover = true;
          } else {
            room.hover = false;
          }
        });
        this.checkCollisions(this.corridors, mousePos, function(corridor, isColliding){
          if (isColliding) {
            corridor.hover = true;
          } else {
            corridor.hover = false;
          }
        });
      },
      handleScroll: function(e){
        //TODO: translate during zoom based on mouse position
        e.preventDefault();
        var delta = e.wheelDelta ? e.wheelDelta/120 : 0;
        if (delta) {
          var factor = 1+delta/10;
          this.transforms.scaleFactor *= factor;
          this.draw();
        }
      },
      drawGrid: function () {
        var ctx = this.context;
        for (var i = SCALE; i < this.canvas.width; i+=SCALE) {
          ctx.beginPath();
          ctx.moveTo(i, 0);
          ctx.lineTo(i, this.canvas.height);
          ctx.lineWidth=LINEWIDTH;
          ctx.strokeStyle = 'black';
          ctx.stroke();
        }
        for (var i = SCALE; i < this.canvas.height; i+=SCALE) {
          ctx.beginPath();
          ctx.moveTo(0, i);
          ctx.lineTo(this.canvas.width, i);
          ctx.lineWidth=LINEWIDTH;
          ctx.strokeStyle = 'black';
          ctx.stroke();
        }
      },
      draw: function () {
        var ctx = this.context;
        ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
        ctx.fillRect(0, 0, this.canvas.width, this.canvas.height);
        ctx.save();
        ctx.scale(this.transforms.scaleFactor, this.transforms.scaleFactor);
        ctx.translate(this.transforms.panX, this.transforms.panY);
        for (var i = 0; i < this.rooms.length; i++) {
          this.rooms[i].draw(ctx);
        }
        for (var i = 0; i < this.corridors.length; i++) {
          this.corridors[i].draw(ctx);
        }
        this.drawGrid();
        for (var i = 0; i < this.doors.length; i++) {
          this.doors[i].draw(ctx);
        }
        ctx.restore();
      }
    };

    $(function() {
      $.ajax({
        url: '/generator/ajax/map_data/',
        dataType: 'json',
        success: handleRequest
      });
    });

    function handleRequest(data) {
      var rooms = data.rooms.map(function(r) {
        return new Room(r.x, r.y, r.width, r.height, r.isActive, 1);
      });
      console.log(rooms[0]);
      dungeonMapper.rooms = rooms;
      dungeonMapper.corridors = [];
      dungeonMapper.doors = [];
      dungeonMapper.start();
    }
  </script>
{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
  	<div class="col-md-12 text-center">
  		<h1>Canvas Test</h1>
  		<div>- Generate Infinite Content -</div>
  	</div>
    <div class="col-md-12">
      <canvas id="canvas" width="500" height="500" style="border:1px solid #000000;">
      </canvas>
    </div>
  </div> <!-- row -->
</div> <!-- container -->

{% endblock %}